#!/usr/bin/bash

git clone https://github.com/file/file
pushd file

cp /usr/share/automake-1.16/compile .
cp /usr/share/automake-1.16/config.sub .
cp /usr/share/automake-1.16/config.guess .
cp /usr/share/automake-1.16/install-sh .
cp /usr/share/automake-1.16/missing .
cp /usr/share/libtool/build-aux/ltmain.sh .

autoheader
aclocal
automake -a -c
autoconf
./configure

make -j10
make install

popd

cp /usr/local/bin/file out/ 
cp /usr/local/lib/libmagic.so out/
cp /usr/local/share/misc/magic.mgc out/
cp src/magic.h out/

pushd out
chmod 777 file
chmod 666 libmagic.so
chmod 666 magic.mgc
chmod 666 magic.h
chown nobody.nogroup file
chown nobody.nogroup libmagic.so
chown nobody.nogroup magic.mgc
chown nobody.nogroup magic.h
popd

